@startuml uml
package seminar {
    !include ./analyse/Analyse.puml
    !include ./gui/Gui.puml
    !include ./Worker.puml



    Worker --> MainWindow
    Worker --> PassiveAnalyser
    Worker --> analyse.network.Structure
    MainWindow --> Worker
    PassiveAnalyser -|> Worker

}
@enduml
@startuml
    User -> Start: Start Program
    Start -> Start: CMD interpretation
    Start -> Worker: Create
    Start -> Worker: Start
    Worker -> MainWindow: Start

    User -> Worker: End
@enduml