@startuml gui
package gui {
    class MainWindow {
        + worker: Worker
        + event_queue: queue.Queue
        + window_structure = Structure
        + passive_output: tk.Text
        + passive_power_button: tk.Button
        --
        + __init__(worker)
        + setup_layout(): void
        + passive_power_button_pressed(): void
        + refresh(): void
        + passive_print(string: string): void
        + structure_print(string: string): void
        + open(): void
        + close(): void
    }

    class Structure {
        + passive_structure: tk.Text
        --
        + __init__(main_window: MainWindow)
        + set(string: string): void
    }

    MainWindow --> Structure
}
@enduml